//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace AutoUpdate.Core.Data
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.ServiceModel;
    using System.Text;

    [MessageContract]
    public class UploadFileInfo : FileBaseInfo
    {
        /// <summary>
        /// 文件流数据
        /// </summary>
        [MessageBodyMember]
        public  Stream FileStream
        {
            get;
            set;
        }
    }
}

