//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace AutoUpdate.Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class FilePathInfo
	{
		/// <summary>
		/// 文件物理路径
		/// </summary>
		public  string PhysicalPath
		{
			get;
			set;
		}

		/// <summary>
		/// 文件相对路径
		/// </summary>
		public  string RelativePath
		{
			get;
			set;
		}

	}
}

