//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace AutoUpdate.Model
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class FileBaseInfo
	{
		/// <summary>
		/// 文件名称
		/// </summary>
		public  string FileName
		{
			get;
			set;
		}

		/// <summary>
		/// 文件大小
		/// </summary>
		public  long FileSize
		{
			get;
			set;
		}

	}
}

