//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace AutoUpdate.Core.Data
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.ServiceModel;
    using System.Text;

	public enum ResultType : int
	{
		/// <summary>
		/// 操作成功
		/// </summary>
		Success,
        /// <summary>
        /// 操作失败
        /// </summary>
        Fail,
		/// <summary>
		/// 警告
		/// </summary>
		Warning,
		/// <summary>
		/// 错误信息
		/// </summary>
		Error,
		/// <summary>
		/// 非法操作
		/// </summary>
		IllegalOperation,
	}
}
