//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace AutoUpdate.ICore.IService
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.ServiceModel;
    using System.Text;
    using AutoUpdate.Core.Data;

    [ServiceContract]
    public interface IOperateFile
    {
        /// <summary>
        /// 下载文件
        /// </summary>
        /// <param name="downFileInfo"></param>
        /// <returns></returns>
        [OperationContract]
        DownloadFileResult DownloadFile(DownloadFileInfo downFileInfo);
        /// <summary>
        /// 下载文件
        /// </summary>
        /// <param name="downFiles"></param>
        /// <returns></returns>
        [OperationContract]
        List<DownloadFileResult> BatchDownloadFile(List<DownloadFileInfo> downFiles);
        /// <summary>
        /// 上传文件
        /// </summary>
        /// <param name="uploadFile"></param>
        /// <returns></returns>
        UploadFileResult UploadFile(UploadFileInfo uploadFile);
        /// <summary>
        /// 上传文件
        /// </summary>
        /// <param name="uploadFiles"></param>
        /// <returns></returns>
        List<UploadFileResult> BatchUploadFile(List<UploadFileInfo> uploadFiles);

    }
}

