//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace AutoUpdate.ICore.IService
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.ServiceModel;
    using System.Text;
    using AutoUpdate.Core.Data;

    [ServiceContract]
    public interface IUpdateSystem
    {
        /// <summary>
        /// 获取版本配置文件信息
        /// </summary>
        /// <returns>返回配置文件信息内容</returns>
        [OperationContract]
        UpdateConfig GetVersionConfig();
        /// <summary>
        /// 更新文件上传之后，生成新版本配置文件
        /// </summary>
        /// <param name="config">更新配置文件</param>
        /// <returns>返回服务器上的存放路径</returns>
        [OperationContract]
        string GenerateVersionConfig(UpdateConfig config);
        /// <summary>
        /// 上传系统更新文件
        /// </summary>
        /// <param name="uploadFileInfo">文件信息</param>
        /// <returns>返回上传结果信息</returns>
        [OperationContract]
        UploadFileResult UploadUpdateSystemFile(UploadFileInfo uploadFileInfo);
        /// <summary>
        /// 下载更新系统的文件
        /// </summary>
        /// <param name="downFileInfo">下载文件信息</param>
        /// <returns>文件下载结果信息</returns>
        [OperationContract]
        DownloadFileResult DownloadUpdateSystemFile(DownloadFileInfo downFileInfo);
    }
}

