//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace AutoUpdateServer
{
	using AutoUpdate.Model;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IOperateFile 
	{
		void DownFile(DownFileInfo downFileInfo);

		/// <param name="uploadFile">文件上传信息</param>
		void UploadFile(UploadFileInfo uploadFile);

		void UploadFile(List<UploadFileInfo> uploadFiles);

		void DownFile(List<DownFileInfo> downFiles);

	}
}

