//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace AutoUpdateServer
{
	using AutoUpdate.Model;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class UpdateSystem : IUpdateSystem
	{
		/// <summary>
		/// 配置文件存储路径
		/// </summary>
		private string configPath
		{
			get;
			set;
		}

		/// <summary>
		/// 配置文件存储路径
		/// </summary>
		public  string ConfigPath
		{
			get;
			private set;
		}

		public  string GetVersionConfig()
		{
			throw new System.NotImplementedException();
		}

		public  void GenerateVersionConfig()
		{
			throw new System.NotImplementedException();
		}

		public  void DownFile(DownFileInfo downFileInfo)
		{
			throw new System.NotImplementedException();
		}

		/// <param name="uploadFile">文件上传信息</param>
		public  void UploadFile(UploadFileInfo uploadFile)
		{
			throw new System.NotImplementedException();
		}

		public  void UploadFile(List<UploadFileInfo> uploadFiles)
		{
			throw new System.NotImplementedException();
		}

		public  void DownFile(List<DownFileInfo> downFiles)
		{
			throw new System.NotImplementedException();
		}

	}
}

